# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finAnalytics', '0002_stockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='trade_date',
            field=models.CharField(max_length=20),
        ),
    ]
