# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finAnalytics', '0003_auto_20160712_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='high_proce',
            new_name='high_price',
        ),
    ]
