# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finAnalytics', '0004_auto_20160712_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='trade_date',
            field=models.DateField(max_length=20),
        ),
    ]
