# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finAnalytics', '0005_auto_20160712_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='adj_close',
            new_name='adjusted',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='trade_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='open_price',
            new_name='open',
        ),
    ]
